### ISSUE TITLE
Set time to CET

### ISSUE THREAD

**Issue by agtoever** [RubenNL/PlaceNL-docker#1]
Add Env variable "TZ: CET" to Docker Compose file to set time to CET (instead of UTC).
This reports the times in Firefox in NL time. This makes sense when connecting to Firefox and checking next pixel place time...

**Comment by RubenNL** [comment]
Thanks for the suggestion! I've just pushed an update: https://github.com/RubenNL/PlaceNL-docker/commit/7a61326ffa5d775922c724dab8a8b1217203e04d.
